# network configuration for GRASP-Net, down-up scale 2

---
architecture: grasp_quad
modules:
    dus: 2
    entropy_bottleneck: 8
    scaling_ratio: 0.25 # key param
    point_mul: 10 # key param
    skip_mode: -1 # key param
    noise: 0.125
    fit_num: 30
    fit_radius: 16
    sample_radius: 2
    res_enc:
        model: point_res_enc
        mlp_dims: [3, 16, 32, 64, 64, 128]
        fc_dims: [128, 64, 16]
        residual_mode: quad_fitting
        fit_num: 30
        fit_radius: 16
        sample_radius: 2
        matching_algorithm: assignment
    vox_enc:
        model: spcnn_down2
        dims: [16, 32, 8]
    vox_dec:
        model: spcnn_up2
        dims: [8, 64, 32]
    res_dec:
        model: mlpdecoder_sparse
        dims: [-1, 128, 128, 64]
