# network configuration for GRASP-Net, down-up scale 2

---
architecture: grasp
modules:
    dus: 2
    entropy_bottleneck: 8
    scaling_ratio: -1 # key param
    point_mul: -1 # key param
    skip_mode: -1 # key param
    noise: 0.125
    res_enc:
        model: point_res_enc
        mlp_dims: [3, 16, 32, 64, 64, 128]
        fc_dims: [128, 64, 16]
    vox_enc:
        model: spcnn_down2
        dims: [16, 32, 8]
    vox_dec:
        model: spcnn_up2
        dims: [8, 64, 32]
    res_dec:
        model: mlpdecoder_sparse
        dims: [-1, 128, 128, 64]
