architecture: diffusion
modules:
    dus: 2
    entropy_bottleneck: 8
    scaling_ratio: 0.125 # key param
    point_mul: 10 # key param
    skip_mode: -1 # key param
    noise: 0.125
    res_enc:
        model: point_res_enc
        mlp_dims: [3, 16, 32, 64, 64, 128]
        fc_dims: [128, 64, 16]
    vox_enc:
        model: spcnn_down2
        dims: [16, 32, 8]
    vox_dec:
        model: spcnn_up2
        dims: [8, 64, 32]
    res_dec:
        model: diffusion_decoder_v2
        training_steps: 200
        beta_1: 0.0001
        beta_T: 0.05
        num_points: 10
        t_emb_dim: 8
        feature_dim: 16
        init_method: quad
        num_points_fit: 30
        thres_dist: 20
        sample_radius: 2
        loss_mode: CD
