# Copyright (c) 2010-2022, InterDigital
# All rights reserved. 

# See LICENSE under the root folder.


# Optimization configuration

---
n_epoch: 50
main_args:
    lr: 0.0008
    opt_args: [0.9, 0.999, 0]
    schedule_args: ['cosine_annealing', 50]
loss_args:
    loss: cd_sparse
    alpha: 5
    beta: 1
clip_max_norm: -1